---
title: "Homework11"
author: "Emma Estabrook"
date: "4/15/2020"
output: html_document
---

```{r}
##################################################
# function: regStats
# fits linear model, extracts statistics
# input: 2-column data frame (x and y)
# output: slope, p-value, and r2
#------------------------------------------------- 
regStats <- function(d=NULL) {
             if(is.null(d)) {
               xVar <- runif(10)
               yVar <- runif(10)
               d <- data.frame(xVar,yVar)
             }
  . <- lm(data=d,d[,2]~d[,1])
  . <- summary(.)
  statsList <- list(Slope=.$coefficients[2,1],
                    pVal=.$coefficients[2,4],
                    r2=.$r.squared)
  return(statsList)

}

# Preliminaries -----------------------------

library(TeachingDemos)
char2seed("Freezing March")

#--------------------------------------------
# Global variables
fileFolder <- "Homework11_Files/"
nFiles <- 2
fileOut <- "StatsSummary.csv"
#--------------------------------------------

# Create 100 random data sets
fileNames <- list.files(path=fileFolder)

# Create data frame to hold file summary statistics
ID <- seq_along(fileNames)
fileName <- fileNames
slope <- rep(NA,nFiles)
pVal <- rep(NA,nFiles)
r2 <- rep(NA,nFiles)

statsOut <- data.frame(ID,fileName,slope,pVal,r2)

# batch process by looping through individual files
for (i in seq_along(fileNames)) {
  data <- read.table(file=paste(fileFolder,fileNames[i],sep=""),
                     sep=",",
                     header=TRUE) # read in next data file
  
  dClean <- data[complete.cases(data),] # get clean cases
  
  . <- regStats(dClean) # pull regression stats from clean file
  statsOut[i,3:5] <- unlist(.) # unlist, copy into last 3 columns
  
}
# set up output file and incorporate time stamp and minimal metadata
  write.table(cat("# Summary stats for ",
                    "batch processing of regression models","\n",
                    "# timestamp: ",as.character(Sys.time()),"\n",
                    "# ELE","\n",
                    "# ------------------------", "\n",
                    "\n",
                    file=fileOut,
                    row.names="",
                    col.names="",
                    sep=""))
  
# now add the data frame
  write.table(x=statsOut,
              file=fileOut,
              row.names=FALSE,
              col.names=TRUE,
              sep=",",
              append=TRUE)
```

```{r}
##################################################
# function: regStats
# fits linear model, extracts statistics
# input: 2-column data frame (x and y)
# output: slope, p-value, and r2
#------------------------------------------------- 
regStats <- function(d=NULL) {
             if(is.null(d)) {
               xVar <- runif(10)
               yVar <- runif(10)
               d <- data.frame(xVar,yVar)
             }
  . <- lm(data=d,d[,2]~d[,1])
  . <- summary(.)
  statsList <- list(Slope=.$coefficients[2,1],
                    pVal=.$coefficients[2,4],
                    r2=.$r.squared)
  return(statsList)

}

# Preliminaries -----------------------------

library(TeachingDemos)
library(ggplot2)
char2seed("Freezing March")

#--------------------------------------------
# Global variables
fileFolder <- "Homework11_Files/"
nFiles <- 2
fileOut <- "StatsSummary.csv"
#--------------------------------------------

# Create 100 random data sets
fileNames <- list.files(path=fileFolder)

# Create data frame to hold file summary statistics
ID <- seq_along(fileNames)
fileName <- fileNames
slope <- rep(NA,nFiles)
pVal <- rep(NA,nFiles)
r2 <- rep(NA,nFiles)

statsOut <- data.frame(ID,fileName,slope,pVal,r2)

# batch process by looping through individual files
for (i in seq_along(fileNames)) {
  data <- read.table(file=paste(fileFolder,fileNames[i],sep=""),
                     sep=",",
                     header=TRUE) # read in next data file
  
  dClean <- data[complete.cases(data),] # get clean cases
  
  . <- regStats(dClean) # pull regression stats from clean file
  statsOut[i,3:5] <- unlist(.) # unlist, copy into last 3 columns
  
}
# batch process by looping to create basic plot
plot_list <- list ()
for (i in seq_along(fileNames)) {
  data <- read.table(file=paste(fileFolder,fileNames[i],sep=""),
                     sep=",",
                     header=TRUE)
  df <- data.frame(data)
  plot <- qplot(x=df$x_var, y=df$y_var)
  plot_list[[i]] = plot
}

for (i in seq_along(fileNames)) {
  file_name <- paste("my_plot_", i, ".pdf", sep="")
  pdf(file_name)
  print(plot_list[[i]])
  dev.off()
}

# set up output file and incorporate time stamp and minimal metadata
  write.table(cat("# Summary stats for ",
                    "batch processing of regression models","\n",
                    "# timestamp: ",as.character(Sys.time()),"\n",
                    "# ELE","\n",
                    "# ------------------------", "\n",
                    "\n",
                    file=fileOut,
                    row.names="",
                    col.names="",
                    sep=""))
  
# now add the data frame
  write.table(x=statsOut,
              file=fileOut,
              row.names=FALSE,
              col.names=TRUE,
              sep=",",
              append=TRUE)
```


```

